### PR TITLE
authentication middleware added and is working

### PR DESCRIPTION
**Pull request by AlishaPanday**

### CODE REVIEW

**Comment by Hisaacs** [comment]
Merging second instance where login authentication has been updated

**Comment by Hisaacs** [comment]
Update login authentication

**Comment by Hisaacs** [comment]
Approved

**Review by AlishaPanday — COMMENTED** [review]
api & html route added, client side js for login and signup added

**Comment by Hisaacs** [comment]
Reviewed for approval

**Review by Hisaacs — APPROVED** [review]

**Review by Foggles — APPROVED** [review]

**Pull request merged**
